version: '3.9'
services:
  backend:
    build:
      context: .
      dockerfile: ./backend/container/Dockerfile
    # build: ./backend/container
    ports:
      - "8080:8080"
    env_file:
      - ./backend/.env
  frontend:
    build:
      context: .
      dockerfile: ./frontend/container/Dockerfile
    ports:
      - "3000:8080"
