name: Match-Display-Frontend-Deploy

# Run workflow on every push to main branch
on: 
  push: 
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Workflow jobs
jobs:

  deploy:
    name: Deploy to Heroku
    runs-on: ubuntu-latest
    steps:
    
    # Clone the repo
    - name: Checkout
      uses: actions/checkout@v2

    # PUSH the Docker image to Heroku Container Registry
    - name: Docker Build, Deploy and Publish
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        HEROKU_EMAIL: ${{ secrets.HEROKU_EMAIL }}
        DOCKERFILE_NAME: "./frontend/container/Dockerfile"
        DOCKER_OPTIONS: "--no-cache"
        APP_NAME: ${{ 'match-desplay-frontend' }}
        REACT_APP_MATCH_DISPLAY_URL: ${{ secrets.BACKEND_URL }}
      run: |
        echo successfully run
