name: Match-Display-Frontend-Deploy

# Run workflow on every push to main branch
on: 
  push: 
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Workflow jobs
jobs:

  deploy:
    name: Deploy to Heroku
    runs-on: ubuntu-latest
    steps:
    
    # Clone the repo
    - name: Checkout
      uses: actions/checkout@v2

    # Push to Heroku Container Registry
    - name: Login to Heroku Container registry
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: heroku container:login
