name: Match-Display-Frontend-Deploy

# Run workflow on every push to main branch
on: 
  push: 
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
  APP_NAME: "match-display-frontend"

# Workflow jobs
jobs:

  deploy:
    name: Deploy to Heroku
    runs-on: ubuntu-latest
    steps:
    
    # Clone the repo
    - name: Checkout
      uses: actions/checkout@v2

    # Push to Heroku Container Registry
    - name: Login to Heroku Container registry
      
      run: heroku container:login

    - name: Build and push
      run: heroku container:push -a ${ APP_NAME } web
    
    - name: Release
      run: heroku container: release -a ${ APP_NAME } web

